name: Publish Release
on:
  release:
    types: [published]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
jobs:
  publish-docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get Tag for Docker
        run: VERSION=$(sed 's/v//' <<< ${{ github.ref_name }}) && echo "::set-output name=tagname::$VERSION"
        id: tagname
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          platforms: linux/amd64,linux/arm64
          file: ./docker/Dockerfile
          tags: ringojs/ringojs:${{ steps.tagname.outputs.tagname }}
          push: true
