name: Build and Test
on: [push, workflow_dispatch]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - run: ./gradlew build
